# build browser
FROM node:16 AS browser-builder
WORKDIR /app
COPY ./browser/* .
RUN yarn && \
    yarn build

# python
FROM python:3.10-slim
WORKDIR /app
COPY ./server/* .
COPY --from=browser-builder /app/build ./build  
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    /usr/local/bin/python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    rm ./.env

EXPOSE 9000
CMD [ "python", "app.py" ]